# Setup
title:        Microconsultation Marketplace
tagline:      An Unsolicited Proposal of Skylight Digital
baseurl:      "https://skylight-hq.github.io/microconsultation/"
paginate:     1

# About/contact
author:
  name:       Robert L. Read and Skylight Digital Team
  url:        https://skylight.digital/ 

# Gems
plugins:
  - jekyll-paginate

#Others
markdown: kramdown